x-inheritable: true
type: object
properties:
  redaction-policy:
    type: string
    description: |-
      Possible values:
      - none
      - never

      Do not assume this is a static enumeration; Persona may add new values
      in the future without a versioned update.
    default: none
  write-policy:
    type: string
    description: |-
      Possible values:
      - none
      - write_once

      Do not assume this is a static enumeration; Persona may add new values
      in the future without a versioned update.
    default: none
  computed:
    type: boolean
  required:
    type: boolean
  archived-at:
    type:
      - string
      - 'null'
    format: date-time
    examples:
      - '2023-06-29T23:54:35.293Z'
  deactivated-at:
    type:
      - string
      - 'null'
    format: date-time
    examples:
      - '2023-06-29T23:54:35.293Z'
